name: gelato-magico-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.2.4
  - numpy=1.21.2
  - pandas=1.3.3
  - scikit-learn=1.0.2
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - joblib=1.0.1
  - pip:
    - mlflow==2.8.1
    - azureml-core==1.54.0
    - azureml-mlflow==1.54.0
    - azureml-defaults==1.54.0
    - inference-schema==1.5.1
    - flask==2.0.1
    - python-dateutil==2.8.2
    - pytimezone==2021.3